//RULES TO BE FOLLOWED WHILE CREATING IDENTIFIERS

//1. IDENTIFIER NAME SHOULD NOT START WITH A DIGIT
//2. EXCEPT $ AND _ NO OTHER SPECIAL CHARACTER ARE ALLOWED 

class HelloAndWelcomeToOurAptechJavaFullStackDeveloperCourse
{
}